### ISSUE TITLE
Error evaluation

### ISSUE THREAD

**Issue by MedericFourmy** [tobycollins/IPPE#2]
Hello, thanks a lot for this very useful code.

Is the evaluation of the reprojection error right? It seems that `dx = dy` 

    if (projectedPoints.depth() == CV_32FC1) {   
        dx = projectedPoints.at<Vec2f>(i)[0] - imagePoints.at<Vec2f>(i)[0];   
        // dy = projectedPoints.at<Vec2f>(i)[0] - imagePoints.at<Vec2f>(i)[0];   // currently
        dy = projectedPoints.at<Vec2f>(i)[1] - imagePoints.at<Vec2f>(i)[1];
    }
    else {
        dx = projectedPoints.at<Vec2d>(i)[0] - imagePoints.at<Vec2d>(i)[0];
        // dy = projectedPoints.at<Vec2d>(i)[0] - imagePoints.at<Vec2d>(i)[0];  // currently
        dy = projectedPoints.at<Vec2d>(i)[1] - imagePoints.at<Vec2d>(i)[1];
    }

**Comment by tobycollins** [comment]
Thanks for spotting. This was a regression error when IPPE was modified to support both double and float OpenCV point sets

**Comment by MedericFourmy** [comment]
Ok, thanks for the quick fix.
